### PR TITLE
Export contact and addressbook as vcard + header restructuration fix

### LINKED ISSUE #247: Export Contact
Add option to export a single contact as a vCard

### PR DESCRIPTION
**Pull request by skjnldsv**
Fixes #247 and #248
Waiting for https://github.com/owncloud/core/pull/23891 for the white download icons
- Add option to export an addressbook with all its contacts
- Add option to export a single contact as a vCard

screen

### CODE REVIEW

**Comment by jancborchardt** [comment]
The icons are too close together and look a bit strange on top of each other. I would place them left/right next to each other, with the delete icon on the right.

**Comment by skjnldsv** [comment]
Like this?
Screen

**Comment by jancborchardt** [comment]
Yes, but with more padding. The clickable area of an icon needs to be 44*44px at least.

**Comment by skjnldsv** [comment]
Okay, and what about the mobile view?
It break a lot of stuff.
I think we need to fix the header, using position absolute in css isn't really a good idea for media queries.
screen

**Comment by jancborchardt** [comment]
On mobile it could be shown above each other, it’s the less important view. But on desktop it should look proper.

> I think we need to fix the header, using position absolute in css isn't really a good idea for media queries.

What do you mean by that? The name should always be shown fixed? I would say not because then you have very little space for typing in the fields, when the keyboard is also expanded.

**Comment by skjnldsv** [comment]
I mean, in css, you need to keep a structure.
Using the absolute position in css should only be used for elements that break the cascading structure of your page. In this case, the h2, inputs, buttons, don't break this at all.
We should use either a flexbox or a float, but using absolute break many further possibilities to make a dynamic design, because the element become an independent item and isn't related or linked to elements around it.

This is a good example, the header become broken in mobile view. With a good fluid css design, the elements should at least rearrange to display themselves in the page. Because of the absolute we got div out of the view! Not a good idea!

Unfortunately, a lot of design part in owncloud use the position absolute option and I don't think this is very convenient. :)

**Comment by DeepDiver1975** [comment]
We have the recurring issue that this is not working with 9.0.0 and 9.0.1 because the icon is not in core.
Please add the download icon to the app and use this one until we drop support for 9.0.0 and 9.0.1 (assuming we backport owncloud/core#23891 )

**Comment by skjnldsv** [comment]
Okay, I wasn't sure how to proceed! Thanks Deep! :)

**Comment by jancborchardt** [comment]
@skjnldsv actually the absolute positioning in combination with the correct sizing (width percentage), testing and additional responsive rules works very well everywhere. Floats on the other hand are very difficult to control. Most of the time our layout is simple anyway (and I intend to keep it that way), with 3 elements max next to each other, so absolute positioning is fine.
Hope that explains it? :)

**Comment by Henni** [comment]
@skjnldsv I suggest that this PR should only introduce the export of a single contact.
Let's leave the export function for addressbooks to a different PR as it seems to be a bigger task.

**Comment by jancborchardt** [comment]
Yeah, however the export of the whole address book has higher priority for sure. I would say it should be done first.

**Comment by skjnldsv** [comment]
@Henni this is a single link for the addressbook too. With just a condition to check the dav lib version.
Shouldn't be that hard.

@jancborchardt no, absolute positioning is not fine at all. It works because it's correctly written, but it's terrible coding for css! :p 
It's my humble opinion. And for the float, it's hard to master, but works well (even if now flex is faaar better for positioning and alignement, and should put float on the bench.). :)

For the priority I worked for things that was possible, I couldn't do the addressbook export as long as we didn't have the possibility. Now we do, commit on his way.

Edit: sorry if I sound presumptuous, this isn't on purpose at all, just my opinion (bad or good, you decide) (and i also just came back from work and I'm exhausted ;) )

**Comment by DeepDiver1975** [comment]
> With just a condition to check the dav lib version.
> Shouldn't be that hard.

If I remember correctly we have no mechanism on the js side to read the version number ....

**Comment by DeepDiver1975** [comment]
wait ... oc_config can be used ...

bildschirmfoto von 2016-04-12 09-43-47

**Comment by skjnldsv** [comment]
Thanks @DeepDiver1975 :+1:

**Comment by skjnldsv** [comment]
@DeepDiver1975 ok, seems to work. I don't really like using the controller as it seems easier to pass the whole thing into a ng-shown but parseFloat isn't declared into $scope so I can't use it, it occurred to me it was simpler this way. What do you think? Is this over complicated?

@jancborchardt I will update the header later :)

screen

**Comment by skjnldsv** [comment]
@jancborchardt I fixed the whole header. This is now more flexible and cross-device. 
This is what growing and shrinking looks like:
untitled

ps: because there is no profile picture, the missing space is ok. This should be fixed when the upload form will be done by Henni.

**Comment by jancborchardt** [comment]
@skjnldsv I do like the restructuring except for the removal of the left whitespace. On the most narrow width it’s ok, but on the other widths it’s intentional to line up with the field contents.

**Comment by skjnldsv** [comment]
The left space is because i'm missing the div that replace the img in #342 :)
I can add it if you want?

**Comment by jancborchardt** [comment]
Yeah, it should be added please – it gives better visual balance. You can remove it on the most narrow view if you like, but we need to show the avatar in some way there anyway.

**Comment by skjnldsv** [comment]
No no, I agree with you! :)

**Comment by skjnldsv** [comment]
Rebased and ready to go!

File: js/components/addressBook/addressBook_controller.js [hunk 1]
```diff
@@ -3,6 +3,9 @@ angular.module('contactsApp')
 	var ctrl = this;
 
 	ctrl.showUrl = false;
+	/* globals oc_config */
+	/* eslint camelcase: [2, {properties: "never"}] */
+	ctrl.canExport = parseFloat(oc_config.version.substring(0, 3)) >= 9.1;
```
Comment (DeepDiver1975) [inline js/components/addressBook/addressBook_controller.js]: float is not really the right thing to use - generally speaking since 9.1 and 9.10 are equal in terms of float but not in terms of version. Anyway - there will never be a version higher then 9.2.

BUT: 9.1 is not the correct value to test against. you need to test against 9.0.2 because the fix has been backported

Comment (skjnldsv) [inline js/components/addressBook/addressBook_controller.js]: Oh okay! Thanks! :)
What should I do then?

**Comment by skjnldsv** [comment]
@DeepDiver1975 rebased and fixed.

File: templates/addressBook.html [hunk 2]
```diff
@@ -1,5 +1,12 @@
 <span class="addressBookName">{{ctrl.addressBook.displayName}}</span>
 <span class="utils">
+	<span class="action" ng-show="ctrl.canExport">
+		<span href="{{ctrl.addressBook.url}}?export"
```
Comment (DeepDiver1975) [inline templates/addressBook.html]: span? Doesn't work for me ....

Comment (skjnldsv) [inline templates/addressBook.html]: Do you have the version > 9.0.2?
It works fine here, I don't understand. What's wrong?
screen-34-04

Comment (skjnldsv) [inline templates/addressBook.html]: ... No comment, I didn't realized! ^^
I must have left some testing.

Thanks for the commit.

**Comment by skjnldsv** [comment]
Rebased and waiting for tests before merging.

**Comment by jancborchardt** [comment]
Nice, very cool!
