### PR TITLE
First contact load fix, direct access to contact, contact not in group, group load and order - fix #312

### LINKED ISSUE #312: First contact loading issues
If you have some contacts starting with a special char (like _ for example), it appear on top list but isn't the loaded contact.
- Only happen on page loading.
- Does not happen when selecting a Group.

contacts owncloud

On page loading, reclicking the 'all contact' link make the loaded contact disappear.
contacts owncloud2

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix multiple issues:
- When loading the page directly on a specific group, the first contact loaded was taken from the main contact list which often results by displaying a contact not in the requested group
- When reclicking the already selected group from the list after a fresh page load resulted by the contact details disappearing
- The contacts starting with a special character was being ignored when choosing the first contact to load
- When a uid is specified, the script will  now be looking for it in the specified group, if not found, the first contact of group will be displayed

### CODE REVIEW

**Comment by skjnldsv** [comment]
@Henni :)

**Comment by skjnldsv** [comment]
Rebased with small fix.

**Comment by skjnldsv** [comment]
@jancborchardt a little review here too?

**Comment by tomneedham** [comment]
@skjnldsv everyone knows you can only buy PRs with :beers:  ;) I'll do some batch reviewing when I'm back at the desk this evening.

**Comment by skjnldsv** [comment]
Damn, busted! :3

Edit: @tomneedham, well? :D

**Comment by skjnldsv** [comment]
Fixed a small conflict with the group selection on mobile view.

**Comment by jancborchardt** [comment]
@skjnldsv rebase again :)

@tomneedham you wanna earn your :beers:?

**Comment by skjnldsv** [comment]
Rebased and ready to merge.

File: js/components/contactList/contactList_controller.js [hunk 1]
```diff
@@ -115,21 +130,19 @@ angular.module('contactsApp')
...
-				$route.updateParams({
-					gid: $routeParams.gid,
-					uid: ctrl.contactList[0].uid()
-				});
-			} else {
-				$route.updateParams({
-					gid: $routeParams.gid,
-					uid: undefined
-				});
-			}
```
Comment (Henni) [inline js/components/contactList/contactList_controller.js:130]: why was this else clause removed?

File: js/components/contactList/contactList_controller.js [hunk 2]
```diff
@@ -67,22 +67,37 @@ angular.module('contactsApp')
...
 			ctrl.contacts = contacts;
-			// If desktop version, load first contact (see css for min-width media query)
-			if (!_.isEmpty(ctrl.contacts) && $(window).width() > 768) {
-				ctrl.setSelectedId(_.sortBy(contacts, function(contact) {
-					return contact.fullName();
-				})[0].uid());
+		});
+	});
+
+	// Wait for ctrl.contactList to be updated, load the first contact and kill the watch
```
Comment (Henni) [inline js/components/contactList/contactList_controller.js:77]: I'm planning to move this functionality to the angular routing (probably ui-router) in the future.
But good for now.

File: js/filters/contactGroup_filter.js [hunk 3]
```diff
@@ -22,6 +22,10 @@ angular.module('contactsApp')
 				}
 			}
 		}
-		return filter;
+		if(filter.length === 0) {
+			return contacts;
+		} else {
+			return filter;
+		}
```
Comment (Henni) [inline js/filters/contactGroup_filter.js]: Something like `return filter || contacts;` would also work. But ok like it is.

Comment (skjnldsv) [inline js/filters/contactGroup_filter.js]: Indeed, didn't realized :)
Will edit, it's always better to have cleaner code.

Edit, will not work because filter isn't null/undefined or equal to zero, it's an empty array! :)

File: js/components/contactList/contactList_controller.js (hunk 1 above)
Comment (skjnldsv) [inline js/components/contactList/contactList_controller.js:130]: Because it was causing issues. It was replaced by this test: https://github.com/owncloud/contacts/blob/dabce47b59347b0b0e81be8f266803d77e4afb62/js/components/contactList/contactList_controller.js#L50

Comment (Henni) [inline js/components/contactList/contactList_controller.js:130]: :+1:
